version: '3.4'
services:
  crushftp:
    user: "${UID}:${GID}"
    image: 'crushftp/crushftp11:11.3.0_0'
    container_name: crushftp
    ports:
      - '8081:8080'
      - '9091:9090'
      - '8443:443'
    environment:
      CRUSHFTP_ADMIN_PASSWORD: "changeme"
    volumes:
    - ./CrushFTP11/:/app/CrushFTP11:rw
volumes:
  CrushFTP11:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}
